title: The Axcora Technology
slug: The Axcora
description: Solusi Website Aplikasi dan Point of sale system untuk bisnis mu.
cover: assets/img/pembuatanwebsite.webp
gst: XkcKjKZqNUkChwJXMj5uDjDns6etXvakir
url: https:/www.axcora.com
locale: id_ID
navcover: assets/img/menuwebapp.webp
webcover1: assets/img/optimasiseoweb.webp
webcover2: assets/img/webdevelopernew.webp
webcover3: assets/img/singlepageapp-staticsitegenerator-website-dev.webp
webcover4: assets/img/webdev.webp
contact: Contact Axcora
contactinfo: Hubungi kami untuk kebutuhan informasi dan pertanyaan anda. 
contactbtn: Kirim Pesan
address: Ruko Pasar Wisata Juanda Q.07 - Sidoarjo - Indonesia 
phone: +62895339403223 
whatsapp: +6285646104747
storeid: 224387

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag