restoapp: Aplikasi Restoran 
restocover: assets/img/aplikasirestoranonline.webp
restoinfo: Sempurnakan kebutuhan akan usaha kuliner dengan menggunakan app kami, kemudahan dalam integrasi dan bekerja via standalon fastfood mode, maupun penggunaan pencatatan meja dengan pembagian skema, waiters tablet dan mobile order, kitchen print maupun display screen, kasir point of sale penjualan dan admin backoffice all in one via resto app. Plus bonus integrasi dengan website restoran cafe rumah makan. 
restobtn: Resto App Info
restolink: /aplikasirestoran.html
tokoapp: Aplikasi Toko 
tokocover: assets/img/aplikasitokominimarket.webp
tokoinfo: Kebutuhan terbaik untuk usaha toko shop minimarket dengan aplikasi toko kami. 
tokobtn: Toko App Info
tokolink: /aplikasitoko.html
androidapp: Aplikasi Android 
androidcover: assets/img/aplikasiandroid.webp
androidinfo: Pembuatan aplikasi android untuk informasi bisnis mu. 
androidbtn: Android App Info
androidlink: /aplikasiandroid.html
invoiceapp: Aplikasi Invoice 
invoicecover: assets/img/aplikasiinvoice.webp
invoiceinfo: Mudahkan kebutuhan cetak faktur penjualan invoice mu. 
invoicebtn: Invoice App Info
invoicelink: /aplikasiinvoice.html
bengkelapp: Aplikasi Bengkel 
bengkelcover: assets/img/aplikasibengkel.webp
bengkelinfo: Special kebutuhan penjualan jasa servis bengkel dan penjualan sparepart. 
bengkelbtn: Bengkel App Info
bengkellink: /aplikasibengkel.html
cargoapp: Aplikasi Kargo 
cargocover: assets/img/aplikasicargo.webp
cargoinfo: Ekspedisi kargo pengiriman dengan cek resi dan pembukuan detail plus invoice.
cargobtn: Cargo App Info
cargolink: /aplikasicargo.html
bookingapp: Aplikasi Booking 
bookingcover: assets/img/aplikasibookingonline.webp
bookinginfo: Hotel penginapan villa guest house home stay restoran reservasi system. 
bookingbtn: Booking App Info
bookinglink: /aplikasibooking.html